# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ff7fa4571fa045e286bc4a21407af8e77326b944b391574aee45e57ae1e41af80bf3e731f21742e4dd5d117fe7ab3d39081b57f5349fd1447aed6b61318cda3

test:
  secret_key_base: b3854b85e88a60f9f7be5694b547f36383dd4beb6c9476416381d3c46c2774ebd063556f2362ab5d3f5fb16a000f26764f27a6f9653a9e131186fb2fb06a74eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
